---
parser: "@typescript-eslint/parser"
extends: 
    - airbnb-base
    - plugin:@typescript-eslint/recommended
    - plugin:promise/recommended
parserOptions:
    project: ./tsconfig.json
    sourceType: module
rules:
    "@typescript-eslint/explicit-function-return-type": error
    quotes:
        - error
        - double
    linebreak-style:
        - error
        - windows
    no-plusplus:
        - error
        - allowForLoopAfterthoughts: true
    no-console: off
env:
    node: true
settings:
    import/resolver:
        node:
            extensions:
                - .js
                - .ts
                - .tsx
    import/parsers:
        "@typescript-eslint/parser": 
            - .ts
            - .tsx