# ----------IMPORTANT, Read before change ------------------
# Make sure to run npm run eslint after changing this file
# ESlint plugin will not provide any visual warnings if the
# settings are wrong, please manually verify the change
# ----------------------------------------------------------
---
# Use to parser type script files so that JS rules can apply
parser: "@typescript-eslint/parser"
extends:
    - airbnb-base
    - plugin:@typescript-eslint/recommended
    - plugin:promise/recommended
    - plugin:prettier/recommended
    # Disables typescript related rules that conflict with prettier
    - prettier/@typescript-eslint
parserOptions:
    project: ./tsconfig.json
    # Required to properly parse import statement
    sourceType: module
rules:
    "@typescript-eslint/explicit-function-return-type": error
    quotes:
        - error
        - double
    linebreak-style:
        - error
        - windows
    no-plusplus:
        - error
        - allowForLoopAfterthoughts: true
    no-console: off
env:
    # Defined all global node variables
    node: true
settings:
    # Setting for eslint-plugin-import to properly handle ts import
    import/resolver:
        node:
            extensions:
                - .js
                - .ts
    # Setting for eslint-plugin-import be able to parse typescript files
    import/parsers:
        "@typescript-eslint/parser":
            - .ts
